
- name: install packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true


- name: add docker gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: install docker-ce
  apt:
    pkg:
      - docker-ce={{ docker_version }}
    
    update_cache: true

- name: install docker
  pip:
    name: docker



- name: create directory
  file:
    path: /usr/lib/systemd/system/docker.service.d
    state: directory

- name: set mount flags
  copy:
    dest: /usr/lib/systemd/system/docker.service.d/mount_flags.conf
    content: |
      [Service]
      MountFlags=shared
  register: mount_flags_updated

- name: reload daemon
  systemd:
    daemon_reload: yes
  when: mount_flags_updated is changed
  register: system_daemon_reload

- name: amend permissions
  copy:
    content: '{ "group": "dockerroot" }'
    dest: /etc/docker/daemon.json
  register: docker_daemon_config

- name: restart docker service
  service:
    name: docker
    state: restarted
    enabled: yes
  

- name: add user to docker group
  become: true
  user:
    name:  "{{ rke_ssh_user }}"
    groups: docker
    append: yes
  register: user_task


- name: login as docker user
  shell: |
    su -c ' docker login xxx:5000 -u xxxx -p xxxxx ' "{{ rke_ssh_user }}"
   become: yes
   become_user: "{{ ansible_ssh_user }}"
  when: 
    # if use ansible_connection=local, the var ansible_ssh_user will not defined
    - ansible_connection != 'local'
    - ansible_ssh_user is defined
    - ansible_ssh_user != 'root'

- name: set key
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '~/.ssh/test') }}"


- name: sysctl settings
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
  register: sysctl_k8s_conf

- name: load sysctl settings
  command: sysctl --system
  when: sysctl_k8s_conf is changed



- name: remove swap
  lineinfile:
    path: /etc/fstab
    state: absent
    regexp: '^[^\s]+\s+[^\s]+\s+swap\s+'
  register: remove_swap_volumes

- name: disable swap
  command: swapoff --all
  when: remove_swap_volumes is changed
